---
title: "02. ASD-Sib-Control comparison"
author: "Diana Tan"
date: "8/23/2019"
output: html_document
---

```{r setup, include = FALSE}

library(psych)
library(tidyverse)
library(DescTools)
library(effsize)
library(here)

```

```{r data import}

load(here("data","main_data.Rda"))

# run this line for data dictionary 
attributes(main_data)

main_data_M <- filter(main_data, gender == 1)
main_data_F <- filter(main_data, gender == 2)

```


---PRELIM ANALYSES---
```{r data visualisation}

### male samples

# rev_masc_score is referred to as masculinity score in MS
ggplot(data = main_data_M, mapping = aes(x = rev_masc_score, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_M, mapping = aes(x = `L_sbal-sn`, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_M, mapping = aes(x = `L_n-sn`, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_M, mapping = aes(x = `L_sn-sto`, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_M, mapping = aes(x = `G_ex-ex`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_M, mapping = aes(x = `G_tr-g`, colour = group)) +
  geom_histogram (binwidth = 1.0)

ggplot(data = main_data_M, mapping = aes(x = `G_ft-ft`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_M, mapping = aes(x = `G_ex-ch`, colour = group)) +
  geom_histogram (binwidth = 1.0)

ggplot(data = main_data_M, mapping = aes(x = `G_sn-prn`, colour = group)) +
  geom_histogram (binwidth = 1.0)

ggplot(data = main_data_M, mapping = aes(x = `G_n-sn`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_M, mapping = aes(x = `G_sn-sto`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_M, mapping = aes(x = `G_n-prn`, colour = group)) +
  geom_histogram (binwidth = 2.0)

## female samples

ggplot(data = main_data_F, mapping = aes(x = rev_masc_score, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_F, mapping = aes(x = `L_sbal-sn`, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_F, mapping = aes(x = `L_n-sn`, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_F, mapping = aes(x = `L_sn-sto`, colour = group)) +
  geom_histogram (binwidth = 0.5)

ggplot(data = main_data_F, mapping = aes(x = `G_ex-ex`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_F, mapping = aes(x = `G_tr-g`, colour = group)) +
  geom_histogram (binwidth = 1.0)

ggplot(data = main_data_F, mapping = aes(x = `G_ft-ft`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_F, mapping = aes(x = `G_ex-ch`, colour = group)) +
  geom_histogram (binwidth = 1.0)

ggplot(data = main_data_F, mapping = aes(x = `G_sn-prn`, colour = group)) +
  geom_histogram (binwidth = 1.0)

ggplot(data = main_data_F, mapping = aes(x = `G_n-sn`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_F, mapping = aes(x = `G_sn-sto`, colour = group)) +
  geom_histogram (binwidth = 2.0)

ggplot(data = main_data_F, mapping = aes(x = `G_n-prn`, colour = group)) +
  geom_histogram (binwidth = 2.0)

```



```{r assumptions testing}

## male samples (for Table 2)
shapiro.test(main_data_M$Area)
shapiro.test(main_data_M$rev_masc_score) 
shapiro.test(main_data_M$`L_sbal-sn`) #not normally distributed
shapiro.test(main_data_M$`L_n-sn`)
shapiro.test(main_data_M$`L_sn-sto`) 
shapiro.test(main_data_M$`G_ex-ex`)
shapiro.test(main_data_M$`G_tr-g`)
shapiro.test(main_data_M$`G_ft-ft`) 
shapiro.test(main_data_M$`G_n-sn`)
shapiro.test(main_data_M$`G_sn-sto`) 

## female samples (for Table 3)

shapiro.test(main_data_F$Area)
shapiro.test(main_data_F$rev_masc_score) #not normally distributed
shapiro.test(main_data_F$`L_sbal-sn`) 
shapiro.test(main_data_F$`L_n-sn`)
shapiro.test(main_data_F$`L_sn-sto`) #not normally distributed
shapiro.test(main_data_F$`G_ex-ex`)
shapiro.test(main_data_F$`G_tr-g`)
shapiro.test(main_data_F$`G_ft-ft`) 
shapiro.test(main_data_F$`G_n-sn`)
shapiro.test(main_data_F$`G_sn-sto`) #not normally distributed

```


---MAIN ANALYSES---

```{r within-sex analyses: males}

## sibs vs controls (for Table 2)

main_data_sibctrl_M <- filter(main_data_M, group != "ASD")
main_data_sibctrl_M$group <- factor(main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$age_yrs, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$age_yrs ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$Area, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$Area ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$Area ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$rev_masc_score, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$rev_masc_score ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$rev_masc_score ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$`L_sbal-sn`, group = main_data_sibctrl_M$group, IQR = TRUE) #not normally distributed
wilcox.test(main_data_sibctrl_M$`L_sbal-sn` ~ main_data_sibctrl_M$group)
Lsbalsn_wilcox <- wilcox.test(main_data_sibctrl_M$`L_sbal-sn` ~ main_data_sibctrl_M$group)
Lsbalsn_z <- qnorm(S2_Lsbalsn_wilcox$p.value/2)
Lsbalsn_effsize <- abs(S2_Lsbalsn_z)/sqrt(99)
#r = .36; d = .77 (see https://www.psychometrica.de/effect_size.html)
cohen.d.ci(d = .77, n = 129, n1 = 30, n2 = 69, alpha = .05)

describeBy(main_data_sibctrl_M$`L_n-sn`, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$`L_n-sn` ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$`L_n-sn` ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$`L_sn-sto`, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$`L_sn-sto` ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$`L_sn-sto` ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$`G_ex-ex`, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$`G_ex-ex` ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$`G_ex-ex` ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$`G_tr-g`, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$`G_tr-g` ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$`G_tr-g` ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$`G_ft-ft`, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$`G_ft-ft` ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$`G_ft-ft` ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$`G_n-sn`, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$`G_n-sn` ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$`G_n-sn` ~ main_data_sibctrl_M$group)

describeBy(main_data_sibctrl_M$`G_sn-sto`, group = main_data_sibctrl_M$group)
t.test(main_data_sibctrl_M$`G_sn-sto` ~ main_data_sibctrl_M$group)
cohen.d(main_data_sibctrl_M$`G_sn-sto` ~ main_data_sibctrl_M$group)


## sibs vs controls vs ASD (included in Tan et al. 2017)

describeBy(main_data_M$rev_masc_score, group = main_data_M$group)
male.aov <- aov(rev_masc_score ~ group, data = main_data_M)
summary(male.aov)
TukeyHSD(male.aov)
```


```{r within-sex analyses: females}

## sibs vs controls (for Table 3)

main_data_sibctrl_F <- filter(main_data_F, group != "ASD")
main_data_sibctrl_F$group <- factor(main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$age_yrs, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$age_yrs ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$Area, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$Area ~ main_data_sibctrl_F$group)
cohen.d(main_data_sibctrl_F$Area ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$rev_masc_score, group = main_data_sibctrl_F$group, IQR = TRUE) #not normally distributed
wilcox.test(main_data_sibctrl_F$rev_masc_score ~ main_data_sibctrl_F$group)
genderscore_wilcox <- wilcox.test(main_data_sibctrl_F$rev_masc_score ~ main_data_sibctrl_F$group)
genderscore_z <- qnorm(genderscore_wilcox$p.value/2)
genderscore_effsize <- abs(genderscore_z)/sqrt(85)
#r = .30; d = .63 (see https://www.psychometrica.de/effect_size.html)
cohen.d.ci(d = .63, n = 85, n1 = 25, n2 = 60, alpha = .05)

describeBy(main_data_sibctrl_F$`L_sbal-sn`, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$`L_sbal-sn` ~ main_data_sibctrl_F$group)
cohen.d(main_data_sibctrl_F$`L_sbal-sn` ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$`L_n-sn`, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$`L_n-sn` ~ main_data_sibctrl_F$group)
cohen.d(main_data_sibctrl_F$`L_n-sn` ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$`L_sn-sto`, group = main_data_sibctrl_F$group, IQR = TRUE) #not normally distributed
wilcox.test(main_data_sibctrl_F$`L_sn-sto` ~ main_data_sibctrl_F$group)
Lsnsto_wilcox <- wilcox.test(main_data_sibctrl_F$`L_sn-sto` ~ main_data_sibctrl_F$group)
Lsnsto_z <- qnorm(Lsnsto_wilcox$p.value/2)
Lsnsto_effsize <- abs(Lsnsto_z)/sqrt(99)
#r = .18; d = .41 (see https://www.psychometrica.de/effect_size.html)
cohen.d.ci(d = .41, n = 85, n1 = 25, n2 = 60, alpha = .05)

describeBy(main_data_sibctrl_F$`G_ex-ex`, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$`G_ex-ex` ~ main_data_sibctrl_F$group)
cohen.d(main_data_sibctrl_F$`G_ex-ex` ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$`G_tr-g`, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$`G_tr-g` ~ main_data_sibctrl_F$group)
cohen.d(main_data_sibctrl_F$`G_tr-g` ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$`G_ft-ft`, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$`G_ft-ft` ~ main_data_sibctrl_F$group)
cohen.d(main_data_sibctrl_F$`G_ft-ft` ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$`G_n-sn`, group = main_data_sibctrl_F$group)
t.test(main_data_sibctrl_F$`G_n-sn` ~ main_data_sibctrl_F$group)
cohen.d(main_data_sibctrl_F$`G_n-sn` ~ main_data_sibctrl_F$group)

describeBy(main_data_sibctrl_F$`G_sn-sto`, group = main_data_sibctrl_F$group, IQR = TRUE) #not normally distributed
wilcox.test(main_data_sibctrl_F$`G_sn-sto` ~ main_data_sibctrl_F$group)
Gsnsto_wilcox <- wilcox.test(main_data_sibctrl_F$`G_sn-sto` ~ main_data_sibctrl_F$group)
Gsnsto_z <- qnorm(Gsnsto_wilcox$p.value/2)
Gsnsto_effsize <- abs(Gsnsto_z)/sqrt(99)
#r = .39; d = .93 (see https://www.psychometrica.de/effect_size.html)
cohen.d.ci(d = .93, n = 85, n1 = 25, n2 = 60, alpha = .05)

## sibs vs controls vs ASD (included in Tan et al. 2017)

describeBy(main_data_F$rev_masc_score, group = main_data_F$group)
female.aov <- aov(rev_masc_score ~ group, data = main_data_F)
summary(female.aov)
TukeyHSD(female.aov)

```