---
title: "03. Graphs"
author: "Diana Tan"
date: "8/23/2019"
output: html_document
---

```{r setup}
library(ggplot2)
library(here)
library(viridis)
library(tidyverse)
```

```{r data import}

load(here("data","main_data.Rda"))

# run this line for data dictionary 
attributes(main_data)

```


```{r prob den graph}
main_data$group_new <- paste(main_data$gender, main_data$group)
main_data$group_new <- gsub("1", "male ", main_data$group_new)
main_data$group_new <- gsub("2", "female ", main_data$group_new)


figure2 <- ggplot(main_data, aes(x = rev_masc_score, y = norm_dist, color = group_new)) +
  geom_point(aes(shape = group_new), size = 2) +
  scale_shape_manual(values = c(3, 1, 2, 8, 16, 17)) +
  geom_line(size = 0.8) +
  scale_color_manual(values = c("#BDB8AD", "#C6D4E1", "#44749D", "#BDB8AD", "#C6D4E1", "#44749D")) +
  theme_classic() +
  theme(legend.title = element_blank()) +
  labs(x = "Facial Masculinity Score", y = "Probability Density")

print(figure2)

ggsave("Figure2.png", 
       plot = figure2,
       units = "cm",
       dpi = 300,
       width = 21,
       height = 10)


sub_data <- main_data %>%
  filter(group != "ASD")

asfarGraph <- ggplot(sub_data, aes(x = rev_masc_score, y = norm_dist, color = group_new)) +
  geom_point(aes(shape = group_new), size = 2) +
  scale_shape_manual(values = c(3, 1, 2, 8, 16, 17)) +
  geom_line(size = 0.8) +
  scale_color_manual(values = c("#BDB8AD", "#C6D4E1", "#44749D", "#BDB8AD", "#C6D4E1", "#44749D")) +
  theme_classic() +
  theme(legend.title = element_blank()) +
  labs(x = "Facial Masculinity Score", y = "Probability Density")

print(asfarGraph)

ggsave("asfarSibsMasc.png", 
       plot = asfarGraph,
       units = "cm",
       dpi = 1000,
       width = 21,
       height = 10)

```

